spring.application.name=paymybuddy
spring.datasource.username=myappuser
spring.datasource.password=Lorelei!?(&é")
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:6060/paymybuddy